---
title: "Exploratory Analysis EHSC 8310"
author: "William Norfolk"
date: "11/3/2019"
output:
  word_document: default
  html_document: default
---

```{r add libs}

library(readxl)
library(dplyr)
library(tidyverse)
library(forcats)
library(ggthemes)
library(knitr)
library(naniar)
library(visdat)
library(gridExtra)
library(ggpubr)

```

```{r load data}
#load data. path is relative to project directory
clean_data <-  readRDS("../Data/processed_data/data_cleaned.rds") 
```


```{r}
glimpse(clean_data)
```

```{r}
site_vs_ecoli <- ggplot(clean_data, aes(x = sample_id, y = final_ecoli)) + geom_bar(stat = "identity")

site_vs_ecoli + xlab("Site Name") + ylab("Final E. coli (cfus)")


```




Lets look at final E. coli as an oucome.

```{r}
ecoli_high_temp_air <- ggplot(clean_data, aes(x = final_ecoli, y = ambient_air_high_c, color = sample_id)) + geom_jitter() + xlab("Final E. coli") + ylab("Ambient Air Temp High (C)")

ecoli_high_temp_air

ecoli_low_temp_air <- ggplot(clean_data, aes(x = final_ecoli, y = ambient_air_low_c, color = sample_id)) + geom_jitter() + xlab("Final E. coli") + ylab("Ambient Air Temp Low (C)")

ecoli_low_temp_air

ecoli_water_temp <- ggplot(clean_data, aes(x = final_ecoli, y = water_temp, color = sample_id)) + geom_jitter() + xlab("Final E. coli") + ylab("Water Temp (C)")

ecoli_water_temp

ecoli_cond <- ggplot(clean_data, aes(x = final_ecoli, y = conductivity, color = sample_id)) + geom_jitter() + xlab("Final E. coli") + ylab("Conductivity")

ecoli_cond

ecoli_ph <- ggplot(clean_data, aes(x = final_ecoli, y = ph, color = sample_id)) + geom_jitter() + xlab("Final E. coli") + ylab("pH")

ecoli_ph
```

```{r}
ggarrange(ecoli_high_temp_air, ecoli_low_temp_air, ecoli_water_temp, ecoli_cond, ecoli_ph, ncol = 3, nrow = 2, common.legend = TRUE, legend = "bottom")


```

```{r}
add_week_count <- clean_data %>% dplyr::mutate(week_count = recode(date,
                                                            "9.11.19" = 1,
                                                            "9.23.19" = 2,
                                                            "9.30.19" = 4,
                                                            "10.3.19" = 5))
```


```{r}

date_freq <- ggplot(add_week_count, aes(x = week_count, y = final_ecoli, color = sample_id)) + geom_line()

date_freq + xlab("Week Number") + ylab("E. coli (CFUs)")
```

```{r}
y <- ggplot(add_week_count, aes(x = sample_id, y = week_count)) 

y + geom_tile(aes(fill = final_ecoli)) +xlab("Site Name") + ylab("Week Number")
```



```{r}
ggplot(add_week_count, aes(x = week_count, y = conductivity)) + geom_jitter()
ggplot(add_week_count, aes(x = week_count, y = ph)) + geom_jitter()
ggplot(add_week_count, aes(x = week_count, y = water_temp)) + geom_jitter()
ggplot(add_week_count, aes(x = week_count, y = ambient_air_high_c)) + geom_jitter()
ggplot(add_week_count, aes(x = week_count, y = ambient_air_low_c)) + geom_jitter()
#ggplot(add_week_count, aes(x = week_count, y = last_rain)) + geom_jitter()
ggplot(add_week_count, aes(x = week_count, y = final_ecoli, color = sample_id)) + geom_jitter()


```

###### Conductivity measures and septic 

```{r}

con <- ggplot(clean_data, aes(x = conductivity, y = final_ecoli, color = sample_id)) + geom_jitter()

con

```


```{r}

con_2 <- ggplot(clean_data, aes(x = exceeds_epa, y = conductivity)) + geom_violin() + geom_jitter(aes(color = sample_id)) + xlab("Exceeds EPA")


con_2
```



